name: LogMsg
version: 1.2.1
author: rfsantos1996
main: com.jabyftw.logmsg.LogMsg
description: Simple plugin to change join and quit messages
permissions:
  logmsg.silent:
    description: 'People can join with no message - quit msg only with OP'
    default: op